apiVersion: v1
kind: Service
metadata:
  name: org2peer1
#  namespace: test-network
spec:
  type: NodePort
  ports:
    - port: 7051
      targetPort: 7051
      nodePort: 30301
      name: grpc
    - port: 7053
      targetPort: 7053
      name: event
    - port: 9443
      targetPort: 9443
      nodePort: 30343
      name: metric
    - port: 5984
      targetPort: 5984
      nodePort: 30384
      name: db
  selector:
    app: org2peer1-deployment
---
apiVersion: v1
kind: Service
metadata:
  name: org2peer2
#  namespace: test-network
spec:
  type: NodePort
  ports:
    - port: 7051
      targetPort: 7051
      nodePort: 30401
      name: grpc
    - port: 7053
      targetPort: 7053
      name: event
    - port: 9443
      targetPort: 9443
      nodePort: 30443
      name: metric
    - port: 5984
      targetPort: 5984
      nodePort: 30484
      name: db
  selector:
    app: org2peer2-deployment