apiVersion: v1
kind: Service
metadata:
  name: orderer1
#  namespace: test-network
spec:
  type: NodePort
  ports:
    - port: 7050
      targetPort: 7050
      nodePort: 30050
      name: grpc
    - port: 8443
      targetPort: 8443
      nodePort: 30043
      name: metric
  selector:
    app: orderer1-deployment
---
apiVersion: v1
kind: Service
metadata:
  name: orderer2
#  namespace: test-network
spec:
  type: NodePort
  ports:
    - port: 7050
      targetPort: 7050
      nodePort: 30051
      name: grpc
    - port: 8443
      targetPort: 8443
      nodePort: 30044
      name: metric
  selector:
    app: orderer2-deployment
---
apiVersion: v1
kind: Service
metadata:
  name: orderer3
#  namespace: test-network
spec:
  type: NodePort
  ports:
    - port: 7050
      targetPort: 7050
      nodePort: 30052
      name: grpc
    - port: 8443
      targetPort: 8443
      nodePort: 30045
      name: metric
  selector:
    app: orderer3-deployment
---
apiVersion: v1
kind: Service
metadata:
  name: orderer4
#  namespace: test-network
spec:
  type: NodePort
  ports:
    - port: 7050
      targetPort: 7050
      nodePort: 30053
      name: grpc
    - port: 8443
      targetPort: 8443
      nodePort: 30046
      name: metric
  selector:
    app: orderer4-deployment
---
apiVersion: v1
kind: Service
metadata:
  name: orderer5
#  namespace: test-network
spec:
  type: NodePort
  ports:
    - port: 7050
      targetPort: 7050
      nodePort: 30054
      name: grpc
    - port: 8443
      targetPort: 8443
      nodePort: 30047
      name: metric
  selector:
    app: orderer5-deployment