apiVersion: v1
kind: Pod
metadata:
  name: fabric-tool
#  namespace: test-network
spec:
  volumes:
    - name: shared-data
      persistentVolumeClaim:
        claimName: shared-pvc
  containers:
    - name: fabrictools
      image: hyperledger/fabric-tools:1.4.4
      imagePullPolicy: Always
      command: ["sh", "-c", "--"]
      args: [ "trap : TERM INT; sleep infinity & wait" ]
      env:
        - name: TZ
          value: "Asia/Bangkok"
        - name: CHANNEL_NAME
          value: test-channel
        - name: CHAINCODE_NAME
          value: mycc
        - name: CHAINCODE_VERSION
          value: "1"
        - name: CORE_PEER_NETWORKID
          value: nid1
        - name: ORDERER_URL
          value: orderer1:7050 #Must be orderer1.blockchain.com for ingress or <<ip>>:<<nodeport>> for nodePort
        - name: ORDERER_CA_TLS
          value: /shared/crypto-config/ordererOrganizations/blockchain.com/orderers/orderer1.blockchain.com/tls/ca.crt
        - name: CORE_PEER_ADDRESS
          value: org1peer1:7051
        - name: CORE_PEER_TLS_ENABLED
          value: "true"
        - name: CORE_PEER_TLS_CERT_FILE
          value: /shared/crypto-config/peerOrganizations/firstorg.com/peers/org1peer1.firstorg.com/tls/server.crt
        - name: CORE_PEER_TLS_KEY_FILE
          value: /shared/crypto-config/peerOrganizations/firstorg.com/peers/org1peer1.firstorg.com/tls/server.key
        - name: CORE_PEER_TLS_ROOTCERT_FILE
          value: /shared/crypto-config/peerOrganizations/firstorg.com/peers/org1peer1.firstorg.com/tls/ca.crt
        - name: CORE_PEER_LOCALMSPID
          value: Org1MSP
        - name: FABRIC_LOGGING_SPEC
          value: info
        - name: CORE_PEER_MSPCONFIGPATH
          value: /shared/crypto-config/peerOrganizations/firstorg.com/users/Admin@firstorg.com/msp
        - name: FABRIC_CFG_PATH
          value: /etc/hyperledger/fabric
      volumeMounts:
        - name: shared-data
          mountPath: /shared