---
apiVersion: v1
kind: ConfigMap
metadata:
  name: monitoring-cm
#  namespace: test-network
data:
  prometheus.yml: |-
    scrape_configs:
      - job_name: 'monitoring'
        # Override the global default and scrape targets from this job every 5 seconds.
        scrape_interval: 5s

        static_configs:
          - targets: ['org1peer1:9443', 'org2peer1:9443', 'org1peer2:9443', 'org2peer2:9443']
            labels:
              group: 'peer'
          - targets: ['orderer1:8443', 'orderer2:8443', 'orderer3:8443', 'orderer4:8443', 'orderer5:8443']
            labels:
              group: 'orderer'

---
kind: Service
apiVersion: v1
metadata:
  name: monitoring
  labels:
    run: monitoring
#  namespace: test-network
spec:
  type: NodePort
  selector:
    name: monitoring
  ports:
  - name: promui
    protocol: TCP
    port: 9090
    targetPort: 9090
    nodePort: 30882
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: monitoring
  labels:
    name: monitoring
#  namespace: test-network
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: monitoring
    spec:
      containers:
      - name: monitoring
        image: prom/prometheus
        volumeMounts:
          - name: config-volume
            mountPath: /etc/prometheus/prometheus.yml
            subPath: prometheus.yml
          - mountPath: /shared
            name: shared
        ports:
        - containerPort: 9090
      volumes:
        - name: config-volume
          configMap:
           name: monitoring-cm
        - name: shared
          persistentVolumeClaim:
            claimName: shared-pvc