apiVersion: v1
kind: PersistentVolume
metadata:
  name: shared-pv
#  namespace: test-network
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  storageClassName: manual
  hostPath:
    path: "/Users/Thirakc/kube/data/test-network/artifacts-config"
#  mountOptions:
#    - hard
#    - nfsvers=4
#  nfs:
#    server: 10.9.211.10
#    path: "/NMOF/test-network/artifacts-config"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: shared-pvc
#  namespace: test-network
spec:
  storageClassName: manual #remove if use nas
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi