apiVersion: v1
kind: Service
metadata:
  name: org1peer1
#  namespace: test-network
spec:
  type: NodePort
  ports:
    - port: 7051
      targetPort: 7051
      nodePort: 30101
      name: grpc
    - port: 7053
      targetPort: 7053
      nodePort: 30103
      name: event
    - port: 9443
      targetPort: 9443
      nodePort: 30143
      name: metric
    - port: 5984
      targetPort: 5984
      nodePort: 30184
      name: db
  selector:
    app: org1peer1-deployment
---

apiVersion: v1
kind: Service
metadata:
  name: org1peer2
#  namespace: test-network
spec:
  type: NodePort
  ports:
    - port: 7051
      targetPort: 7051
      nodePort: 30201
      name: grpc
    - port: 7053
      targetPort: 7053
      name: event
      nodePort: 30203
    - port: 9443
      targetPort: 9443
      nodePort: 30243
      name: metric
    - port: 5984
      targetPort: 5984
      nodePort: 30284
      name: db
  selector:
    app: org1peer2-deployment